export const ERROR_CODES = {
  VALIDATION_FAILED: 'ERR_VALIDATION_FAILED',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  FORBIDDEN: 'ERR_FORBIDDEN',
  NOT_FOUND: 'ERR_NOT_FOUND',
  OTP_INVALID: 'ERR_OTP_INVALID',
  OTP_LOCKED: 'ERR_OTP_LOCKED',
  DUPLICATE_REQUEST: 'ERR_DUPLICATE_REQUEST',
  DOWNSTREAM_UNAVAILABLE: 'ERR_DOWNSTREAM_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
